### PR TITLE
Make fields public for ServerListPingEvent

### PR DESCRIPTION
**Pull request by theaddonn**
This pr just makes some fields public for the `ServerListPingEvent`. This is helpful since you may want to modify stuff like the port or Minecraft Version shown. 
This PR is likely missing some stuff since this would also require to change some underlying python bindings, but eh..

Also, any reason we are using `.h` instead of `.hpp`?

### CODE REVIEW

**Comment by theaddonn** [comment]
This PR instead of making the needed fields public, adds methods to set the local port (ipv4 & pv6) as well as the guid

**Comment by wu-vincent** [comment]
Thank you for the pull request! These fields were intentionally kept readable, as modifying these values doesn't affect their appearance in the server list. I am wondering about the practical usage of making these fields writable with these setters?

**Comment by wu-vincent** [comment]
@Dingsel That makes sense to me, although I think the proxy should ideally handle the ping response from backend servers, rather than the backend servers managing it directly. But I assume the proxies aren't that advanced yet. 

@theaddonn One more thing before I merge this PR—could you also add the Python bindings for these setters?

**Comment by theaddonn** [comment]
@wu-vincent The proxy are that advanced, but it introduces a lot more overhead.. which can easily be avoided by just changing the needed data on the backend server directly.

**Pull request merged**
